### ISSUE TITLE
Missing dependancy

### ISSUE THREAD

**Issue by ntbosscher** [pushcx/quickquestion#1]
Hey @pushcx, just giving your tool a try for entertainment on a Friday morning. I'm not looking for a fix, just thought you might like to know about this error.

```
$ gem install quickquestion
$  /usr/local/lib/ruby/gems/3.3.0/bin/qq say hello
```

Error
```
<internal:/usr/local/Cellar/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- claude/client (LoadError)
```

Tried `gem install claude` which didn't solve the issue.

**Comment by pushcx** [comment]
Thsnks for this bug report. It’s been ages since I tried to make a gem, and I specified the dependencies in a way that would only work on my dev machine.

I think it’s fixed now and I cut a new release, but please reopen if you have any more trouble.

**Comment by ntbosscher** [comment]
Working now, thanks!

```
$ /usr/local/lib/ruby/gems/3.3.0/bin/qq give me the first 10 digits of pi
3.141592653 (Cost: $0.0003)

```
